grid_size: [10, 10, 5] # The size of the 3D grid
start_positions: # The start positions of the drones inside the grid
  - [0, 2, 2]
  - [0, 7, 2]
  
goal_positions: # The goal positions for each drone
  - [9, 3, 2]
  - [9, 6, 2]

obstacle_cells: # The list of cells inside the grid that are considered obstacles
  - [5, 7, 2]
  - [5, 3, 2]

change_altitude: False # Only operate in the XY-plane

# MDP model parameters
step_cost: -1.0
collision_penalty: -50.0
goal_reward: 100.0
discount_factor: 0.98
max_num_steps: 100 # The maximum number of steps before the problem terminates
alpha: 0.5 # Action uncertainty parameter

